language: node_js

node_js:
  - '0.10'

before_script:
  - npm install -g grunt-cli

addons:
  sauce_connect: true

env:
  global:
    - secure: QCidJxcH1yyMgW780fHn9+vD1ybqH/hr6Ej+c3RWmQyzNmtsLTpOcM4iVXf27imLC7spXJ1+9gj7mmECNrHCLiyenvb/ml/hesfNbl0jpHt7EEjmkD/XjOp+47HMk9A3/lUeR4sxIedu1gmwfCdzE5YMJz8cAdUrwmTUd4tWAKw=
    - secure: NdCbGDIVTZYsFbvrtv6MNG+gsn5RCpWxTmiZhzlpADC3kbdrmngR+lTCurTrOtomEXfue2Nsuyf9FEw8RHfDwyNtOPxkkvyRLjEYsFxwFCoM1rSgh5XaRlDwOq6bzur8QlGcerbLumnRZe2i9eABrAezmDgRrd0/s3tWeONxXPw=

  matrix:
    - _BROWSER: "chrome"
      _PLATFORM: "Windows_8"
      _VERSION: "31"
    - _BROWSER: "firefox"
      _PLATFORM: "Linux"
      _VERSION: "25"
    - _BROWSER: "internet_explorer"
      _PLATFORM: "Windows_8"
      _VERSION: "10"
    - _BROWSER: "safari"
      _PLATFORM: "Windows_7"
      _VERSION: "5"
    - _PLATFORM: "Mac"
      _APP: "safari"
      _DEVICE: "iPhone_Simulator"
      _VERSION: "7"
    - _PLATFORM: "Mac"
      _APP: "safari"
      _DEVICE: "iPad_Simulator"
      _VERSION: "7"
    - _PLATFORM: "Linux"
      _BROWSER: "android"
      _TYPE: "tablet"
      _VERSION: "4.0"